version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "fargate-stg-task-base-web.json"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80