version: "3"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfile/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-backend_local}
      - DB_USERNAME=${DB_USER:-backend}
      - DB_PASSWORD=${DB_PASS:-passwd}
    command: sh /usr/local/bin/init.sh
    depends_on:
      - db
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dockerfile/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
    depends_on:
      - app
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: ./dockerfile/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_NAME:-backend_local}
      - MYSQL_USER=${DB_USER:-backend}
      - MYSQL_PASSWORD=${DB_PASS:-passwd}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-passwd}